from __future__ import annotations

import threading
from collections import deque
from dataclasses import dataclass
from typing import Deque, Generic, Optional, TypeVar

from .models import ValidationError


T = TypeVar("T")


@dataclass(frozen=True)
class VersionedBatch(Generic[T]):
    batch_id: str
    generated_policy_version: int
    payload: T
    generated_tokens: int


class BoundedRolloutBuffer(Generic[T]):
    """FIFO rollout buffer enforcing capacity and policy-lag bounds."""

    def __init__(self, max_batches: int = 1, max_policy_lag: int = 1) -> None:
        if max_batches <= 0 or max_policy_lag < 0:
            raise ValueError("invalid rollout buffer limits")
        self.max_batches = max_batches
        self.max_policy_lag = max_policy_lag
        self._batches: Deque[VersionedBatch[T]] = deque()
        self._ids: set[str] = set()
        self.stale_batches = 0
        self.stale_tokens = 0
        self._lock = threading.Lock()

    def put(self, batch: VersionedBatch[T], trainer_policy_version: int) -> None:
        with self._lock:
            lag = trainer_policy_version - batch.generated_policy_version
            if lag < 0:
                raise ValidationError("rollout batch was generated by a future policy")
            if lag > self.max_policy_lag:
                self.stale_batches += 1
                self.stale_tokens += batch.generated_tokens
                raise ValidationError("rollout batch exceeds max_policy_lag")
            if batch.batch_id in self._ids:
                raise ValidationError(f"duplicate rollout batch: {batch.batch_id}")
            if len(self._batches) >= self.max_batches:
                raise BufferError("rollout buffer capacity reached")
            self._batches.append(batch)
            self._ids.add(batch.batch_id)

    def get(self, trainer_policy_version: int) -> Optional[VersionedBatch[T]]:
        with self._lock:
            while self._batches:
                batch = self._batches.popleft()
                self._ids.remove(batch.batch_id)
                lag = trainer_policy_version - batch.generated_policy_version
                if 0 <= lag <= self.max_policy_lag:
                    return batch
                self.stale_batches += 1
                self.stale_tokens += batch.generated_tokens
            return None

    def __len__(self) -> int:
        with self._lock:
            return len(self._batches)
